# Generated by Django 5.0.6 on 2024-05-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPOEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("total_stocks", models.IntegerField()),
                (
                    "total_market_cap",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_traded_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_traded_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
            ],
        ),
    ]
