# Generated by Django 5.0.6 on 2024-05-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("open_vlaue", models.FloatField()),
                ("high_value", models.FloatField()),
                ("low_value", models.FloatField()),
                ("close_value", models.FloatField()),
                ("volume", models.IntegerField()),
                ("turnover", models.FloatField()),
                ("transaction", models.IntegerField()),
            ],
        ),
    ]
