# Generated by Django 5.0.6 on 2024-05-23 02:52

import django.utils.timezone
import picklefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("symbol", models.CharField(max_length=10)),
                ("conf", models.FloatField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("vwap", models.FloatField()),
                ("vol", models.IntegerField()),
                ("prev_close", models.FloatField()),
                ("turnover", models.FloatField()),
                ("trans", models.IntegerField()),
                ("diff", models.FloatField()),
                ("range", models.FloatField()),
                ("diff_percentage", models.FloatField()),
                ("range_percentage", models.FloatField()),
                ("vwap_percentage", models.FloatField()),
                ("days_120", models.FloatField()),
                ("days_180", models.FloatField()),
                ("weeks_high", models.FloatField()),
                ("weeks_low", models.FloatField()),
                ("percentage_change", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="stockdata",
            name="columns",
            field=picklefield.fields.PickledObjectField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockdata",
            name="data",
            field=picklefield.fields.PickledObjectField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
    ]
