# Generated by Django 5.0.6 on 2024-05-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketdata", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockdata",
            old_name="close_value",
            new_name="close",
        ),
        migrations.RenameField(
            model_name="stockdata",
            old_name="high_value",
            new_name="high",
        ),
        migrations.RenameField(
            model_name="stockdata",
            old_name="low_value",
            new_name="low",
        ),
        migrations.RenameField(
            model_name="stockdata",
            old_name="open_vlaue",
            new_name="open",
        ),
        migrations.RemoveField(
            model_name="stockdata",
            name="date",
        ),
    ]
