#/bin/env python

# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k8T91ug1-HAPxvYj9d88EUTIguMZ3QwO
"""

import requests
import pandas as pd
import numpy as np
import openpyxl

url = 'https://www.nepalipaisa.com/Market-Mover.aspx'
html = requests.get(url).content
df_list = pd.read_html(html)
df = df_list[-1]

df1=df.sort_values(by=['Closing Price'])
df1.pop('Symbols')

slice_ = ['% Change']
def highlight_max(s, props=''):
    return np.where(s <= 0, props, '')
df2=df1.style.apply(highlight_max, props='color:red;', axis=0, subset=slice_)\
         .set_properties(subset=slice_)
print(df2)

df1.to_csv('my data.csv')

df2.to_excel("output.xlsx")
